services:
  - type: web
    name: brain-tumor-api
    runtime: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt && python download_model.py
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
